// AUTO-GENERATED by scripts/generateImagePreloadList.js
// Do not edit manually!!! Run `npm run generate:images` or let prestart/prebuild do it.

const PRELOAD_IMAGES: readonly string[] = [
  "/img/articles/cookie.png",
  "/img/articles/handshake.jpg",
  "/img/articles/personInterview.jpg",
  "/img/articles/videoInterview.jpg",
  "/img/bkgs/blue.png",
  "/img/bkgs/cmp.png",
  "/img/bkgs/geometric.png",
  "/img/bkgs/quote.png",
  "/img/companies/AON.png",
  "/img/companies/IBM.png",
  "/img/companies/Oracle.png",
  "/img/companies/PeopleSoft.png",
  "/img/companies/SRHM.png",
  "/img/companies/Success.png",
  "/img/companies/Workday.png",
  "/img/competencyHover/afterHover.png",
  "/img/competencyHover/beforeHover.png",
  "/img/header/brain.png",
  "/img/header/cycle.png",
  "/img/header/digitalInterview.png",
  "/img/listpoint/admin.png",
  "/img/listpoint/airplane.png",
  "/img/listpoint/analytics.png",
  "/img/listpoint/checkboxes.png",
  "/img/listpoint/guide1.png",
  "/img/listpoint/guide2.png",
  "/img/listpoint/guide3.png",
  "/img/listpoint/reports.png",
  "/img/listpoint/statistics.png",
  "/img/listpoint/tracking.png",
  "/img/logo.svg",
  "/img/logo180.png",
  "/img/peopleWorking.png",
];

export function preloadImages(): void {
  for (const src of PRELOAD_IMAGES) {
    const img = new Image();
    img.src = src;
  }
}
