// @ts-check
/**
 * Scans public/img/ recursively and rewrites src/utils/preloadImages.ts with
 * the current list of image files. Run automatically via the prestart /
 * prebuild npm hooks so the list never goes stale.
 * 
 * We pre-load images for the demo because there are a LOT of images on the site
 * and we want to avoid jarring pop-in as the user navigates.
 * Preloading them all at once is a bit heavy but it ensures we
 * have a smooth experience throughout the site.
 * 
 * This is a bit hacky but it ensures we don't have to manually maintain the list
 * of images to preload, and it allows us to keep the preloadImages function
 * simple and efficient (just a loop over a static array of strings).
 * 
 * Note: This script assumes that all images in public/img/ should be preloaded.
 * If there are some images you don't want to preload, you'll need to move them
 * out of that directory or modify the script to exclude them.
 * 
 * Usage: `npm run generate:images` or let it run automatically on start/build.
 */

const fs = require("fs");
const path = require("path");

const IMG_DIR = path.resolve(__dirname, "../public/img");
const OUT_FILE = path.resolve(__dirname, "../src/utils/preloadImages.ts");

const IMAGE_EXTENSIONS = new Set([".png", ".jpg", ".jpeg", ".svg", ".webp", ".gif"]);

/** @param {string} dir @returns {string[]} */
function collectImages(dir) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...collectImages(fullPath));
    } else if (IMAGE_EXTENSIONS.has(path.extname(entry.name).toLowerCase())) {
      // Convert absolute fs path → public URL path (/img/...)
      const relative = path.relative(path.resolve(__dirname, "../public"), fullPath);
      results.push("/" + relative.split(path.sep).join("/"));
    }
  }
  return results.sort();
}

const images = collectImages(IMG_DIR);

const lines = images.map((p) => `  "${p}",`).join("\n");

const content = `// AUTO-GENERATED by scripts/generateImagePreloadList.js
// Do not edit manually!!! Run \`npm run generate:images\` or let prestart/prebuild do it.

const PRELOAD_IMAGES: readonly string[] = [
${lines}
];

export function preloadImages(): void {
  for (const src of PRELOAD_IMAGES) {
    const img = new Image();
    img.src = src;
  }
}
`;

fs.writeFileSync(OUT_FILE, content, "utf8");
console.log(`[generateImagePreloadList] Wrote ${images.length} images to preloadImages.ts`);
